version: '2'
services:
    mysql_db:
        image: mysql:latest
        container_name: mysql_db
        environment:
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - 3306:3306

    pentaho:
        image: daocloud.io/darebeat/ubuntu-pentaho
        container_name: pentaho
        command: /run.sh
        environment:
            - MYSQL_HOST=mysql_db
            - MYSQL_PORT=3306
            - MYSQL_USERNAME=root
            - MYSQL_PASSWORD=password
            - S_Xms=2048m
            - S_Xmx=6144m
            - S_MaxPermSize=256m
        depends_on:
            - mysql_db
        links:
            - mysql_db
        ports:
            - 30000:8080
